# fermat_finite_reductions.py
#
# This script computes the finite reductions of the groups associated
# with representatives of the two Aut(S_F)-orbits of sixers on the
# Fermat cubic.
#
# For each prime p in the list below, a primitive third root of unity
# omega is reduced modulo p. The script constructs the projective
# difference generators in PGL_2(F_p) and computes the orders of the
# subgroups they generate.
#
# The two sets of normalized matrices are those obtained in Appendix B.
#
# Output:
#   - the chosen reduction of omega modulo p;
#   - the orders of the groups associated with the 54- and 18-orbits;
#   - the order of PGL_2(F_p).

from itertools import combinations
from collections import deque
def inv_mod(a, p):
    return pow(a % p, -1, p)


def mat_mod(A, p):
    return tuple(tuple(x % p for x in row) for row in A)


def det2(A, p):
    return (A[0][0] * A[1][1] - A[0][1] * A[1][0]) % p


def mat_sub(A, B, p):
    return (
        ((A[0][0] - B[0][0]) % p, (A[0][1] - B[0][1]) % p),
        ((A[1][0] - B[1][0]) % p, (A[1][1] - B[1][1]) % p),
    )


def mat_mul(A, B, p):
    return (
        (
            (A[0][0] * B[0][0] + A[0][1] * B[1][0]) % p,
            (A[0][0] * B[0][1] + A[0][1] * B[1][1]) % p,
        ),
        (
            (A[1][0] * B[0][0] + A[1][1] * B[1][0]) % p,
            (A[1][0] * B[0][1] + A[1][1] * B[1][1]) % p,
        ),
    )


def mat_inv(A, p):
    d = det2(A, p)
    if d == 0:
        raise ValueError("Singular matrix.")

    d_inv = inv_mod(d, p)

    return (
        ((A[1][1] * d_inv) % p, (-A[0][1] * d_inv) % p),
        ((-A[1][0] * d_inv) % p, (A[0][0] * d_inv) % p),
    )


def normalize_matrix(A, p):
    """
    Normalize a nonzero 2 x 2 matrix modulo scalar multiplication.

    We choose the first nonzero entry, in row-major order, and scale it to 1.
    This gives a canonical representative of the corresponding element of PGL_2.
    """
    A = mat_mod(A, p)
    entries = [A[0][0], A[0][1], A[1][0], A[1][1]]

    for x in entries:
        if x % p != 0:
            lam = inv_mod(x, p)
            return (
                ((A[0][0] * lam) % p, (A[0][1] * lam) % p),
                ((A[1][0] * lam) % p, (A[1][1] * lam) % p),
            )

    raise ValueError("The zero matrix does not define an element of PGL_2.")


def finite_line_matrices(Ms, p):
    """
    Return the five finite matrices

        0, I_2, M_2, M_3, M_4

    modulo p.
    """
    zero = ((0, 0), (0, 0))
    identity = ((1, 0), (0, 1))

    return [zero, identity] + [mat_mod(A, p) for A in Ms]


def pgl_generators(Ms, p):
    """
    Compute the projective classes of the ten pairwise differences A - B.

    The matrices M_i themselves are not normalized projectively before taking
    differences.  Only the differences A - B are normalized in PGL_2.
    """
    mats = finite_line_matrices(Ms, p)
    gens = []

    for A, B in combinations(mats, 2):
        D = mat_sub(A, B, p)

        if det2(D, p) == 0:
            raise ValueError("A difference matrix is singular modulo p.")

        gens.append(normalize_matrix(D, p))

    # Remove repetitions.
    out = []
    seen = set()

    for g in gens:
        if g not in seen:
            out.append(g)
            seen.add(g)

    return out


def pgl_order(Ms, p):
    """
    Compute the order of the subgroup of PGL_2(F_p) generated by the ten
    projective difference classes.
    """
    gens = pgl_generators(Ms, p)

    # Add inverses to speed up the breadth-first search.
    gens = gens + [normalize_matrix(mat_inv(g, p), p) for g in gens]

    identity = normalize_matrix(((1, 0), (0, 1)), p)

    seen = {identity}
    queue = deque([identity])

    while queue:
        h = queue.popleft()

        for g in gens:
            hg = normalize_matrix(mat_mul(h, g, p), p)

            if hg not in seen:
                seen.add(hg)
                queue.append(hg)

    return len(seen)


def fermat_matrices_mod(p, r):
    """
    Normalized Fermat matrices reduced modulo p.

    The element omega is reduced by omega |-> r.
    """
    O54 = [
        ((0, 1 + r), (r, -1)),
        ((-r, r), (0, -1 - r)),
        ((1 + r, 1), (0, r)),
    ]

    O18 = [
        ((0, -1 - r), (-r, 1)),
        ((0, 1), (-1, 1)),
        ((0, r), (1 + r, 1)),
    ]

    return [
        [mat_mod(A, p) for A in M]
        for M in [O54, O18]
    ]


def third_root_of_unity(p):
    """
    Return the least r >= 2 satisfying r^2 + r + 1 = 0 modulo p.
    """
    return next(r for r in range(2, p) if (r * r + r + 1) % p == 0)


def pgl2_order(p):
    return p * (p * p - 1)


for p in [7, 13, 19, 31, 37, 43]:
    r = third_root_of_unity(p)
    orders = [pgl_order(M, p) for M in fermat_matrices_mod(p, r)]

    print(p, r, orders, pgl2_order(p))

